#Exploring Global Electricity Access in Schools Through Data Visualization to Support SDG 4 and SDG 7

In [1]:
## introduction

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the Datasets

In [3]:
school = pd.read_csv("school_electricity_access.csv")

In [4]:
school.shape

(675, 4)

In [5]:
school.head()

  Country_Name ISO_Code  Year  Electricity_Access_Percent
0      Albania      ALB  2018                   94.085213
1      Albania      ALB  2019                   97.713760
2      Andorra      AND  2016                  100.000000
3      Andorra      AND  2017                  100.000000
4      Andorra      AND  2018                  100.000000

In [6]:
school.tail()

           Country_Name ISO_Code  Year  Electricity_Access_Percent
670  West Bank and Gaza      PSE  2017                  100.000000
671  West Bank and Gaza      PSE  2018                  100.000000
672  West Bank and Gaza      PSE  2019                  100.000000
673              Zambia      ZMB  2016                   32.369942
674              Zambia      ZMB  2017                   36.401669

In [11]:
school = pd.read_csv("school_electricity_access.csv")

gdp = pd.read_csv("API_NY.GDP.PCAP.CD_DS2_en_csv_v2_46.csv", skiprows=4)
urban = pd.read_csv("API_SP.URB.TOTL.IN.ZS_DS2_en_csv_v2_249.csv", skiprows=4)
electricity = pd.read_csv("API_EG.ELC.ACCS.ZS_DS2_en_csv_v2_158.csv", skiprows=4)
education = pd.read_csv("API_SE.XPD.TOTL.GB.ZS_DS2_en_csv_v2_9902.csv", skiprows=4)

FileNotFoundError: [Errno 2] No such file or directory: 'API_NY.GDP.PCAP.CD_DS2_en_csv_v2_46.csv'

# Filtering School Data for 2019

In [ ]:
school = school[school["Year"] == 2019]

school = school.rename(columns={
    "Country_Name": "Country",
    "Electricity_Access_Percent": "School_Electricity_Access"
})

school = school[["Country", "School_Electricity_Access"]]

school.head()

# Preparing Other Datasets

In [ ]:
year = "2019"

gdp = gdp[["Country Name", year]].rename(columns={year:"GDP_per_capita"})
urban = urban[["Country Name", year]].rename(columns={year:"Urban_population"})
electricity = electricity[["Country Name", year]].rename(columns={year:"Electricity_access"})
education = education[["Country Name", year]].rename(columns={year:"Education_expenditure"})

# Merging the Datasets

In [ ]:
df = school.merge(gdp, left_on="Country", right_on="Country Name")
df = df.merge(urban, on="Country Name")
df = df.merge(electricity, on="Country Name")
df = df.merge(education, on="Country Name")

# Handling Missing Values

In [ ]:
df = df.drop(columns=["Country Name"])
df = df.dropna()

# First Look at the Data

In [ ]:

df.head()

In [ ]:
df.describe()

In [ ]:
df.corr(numeric_only=True)

#Key Visualizations

In [ ]:
df.hist(figsize=(12,8))
plt.show()

In [ ]:
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

In [ ]:
sns.scatterplot(x="GDP_per_capita", y="School_Electricity_Access", data=df)
plt.title("GDP per Capita vs School Electricity Access")
plt.show()

In [ ]:
sns.scatterplot(x="Urban_population", y="School_Electricity_Access", data=df)
plt.title("Urban Population vs School Electricity Access")
plt.show()

In [ ]:
sns.scatterplot(x="Electricity_access", y="School_Electricity_Access", data=df)
plt.title("Total Electricity Access vs School Electricity Access")
plt.show()

In [ ]:
sns.scatterplot(x="Electricity_access", y="School_Electricity_Access", data=df)
plt.title("Total Electricity Access vs School Electricity Access")
plt.show()

In [ ]:
df.to_csv("merged_dataset.csv", index=False)